name = "fiddle-worker-stream-trailing-header"
main = "index.js"

workers_dev = true

# Set this to whatever the current date is for when you start, and then
# update it from time to time.
compatibility_date = "2022-10-19"
